[package]
name = "hw-hash-bruteforce"
version = "0.1.0"
edition = "2024"

[dependencies]
argh = "0.1.13"
hex-simd = "0.8.0"
md5 = "0.7.0"
sha2 = { version = "0.10.8" }

[profile.bench]
lto = true

[profile.release]
lto = true
panic = "abort"
